# Generated by Django 2.0.2 on 2018-02-20 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=50)),
                ('ad_body', models.TextField()),
                ('ad_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.TextField(choices=[('ans_this_wk', 'this_week'), ('ans_this_wk<18', 'this_week<18'), ('ans_ms_this_wk', 'ms_this_week'), ('ans_mr_this_wk', 'mr_this_week'), ('ans_next_wk', 'next_week'), ('ans_next_wk<18', 'next_week<18'), ('ans_ms_next_wk', 'ms_next_week'), ('ans_mr_next_wk', 'mr_next_week')])),
            ],
        ),
    ]
