# Generated by Django 2.0.3 on 2018-03-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0003_auto_20180312_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='answer',
        ),
    ]
