# Generated by Django 2.0.2 on 2018-03-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0006_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
