# Generated by Django 2.0.2 on 2018-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0007_remove_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='template_name',
            field=models.CharField(max_length=20),
        ),
    ]
